services:
  app:
    build:
      context: .
      target: dev
    healthcheck:
      test: sh -c 'apk add curl; curl http://localhost:5000'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - 3000:5000
    volumes:
      - ./src:/opt/epp/src
